name: Build and Publish

on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:

jobs:
  build-and-publish:
    name: Java Gradle
    uses: bakdata/ci-templates/.github/workflows/java-gradle-plugin.yaml@1.64.0
    with:
      java-version: 21
    secrets:
      sonar-token: ${{ secrets.SONARCLOUD_TOKEN }}
      sonar-organization: ${{ secrets.SONARCLOUD_ORGANIZATION }}
      signing-key-id: ${{ secrets.SONATYPE_SIGNING_KEY_ID }}
      signing-password: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      signing-secret-key-ring: ${{ secrets.SONATYPE_SIGNING_SECRET_KEY_RING }}
      ossrh-password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
      ossrh-username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      gradle-publish-key: ${{ secrets.GRADLE_PLUGIN_PUBLISH_KEY }}
      gradle-publish-secret: ${{ secrets.GRADLE_PLUGIN_PUBLISH_SECRET }}
      github-token: ${{ secrets.GH_TOKEN }}
